### ISSUE TITLE
500 Internal Server Error on bitcoin-cli getblock

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/python-teos#104]
Every now and then we get a 500 Internal Server Error from bitcoind when asking for a block. This causes the software to crash since a notified block is supposed to always be there.

```
17/03/2020 12:16:35 [BlockProcessor]: Couldn't get block from bitcoind (error={'code': -342, 'message': "non-JSON HTTP response with '500 INTERNAL SERVER ERROR' from server"}).
Exception in thread Thread-965:
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/circleci/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/circleci/repo/teos/watcher.py", line 143, in do_watch
    logger.info("New block received", block_hash=block_hash, prev_block_hash=block.get("previousblockhash"))
AttributeError: 'NoneType' object has no attribute 'get'
```

I haven't been able to properly reproduce the error.

We could work around it by checking if the received data is None, but the may makes us miss data. It will be better to find the root of the problem.

**Comment by sr-gi** [comment]
Adding this for context in case it can help fixing the issue:

https://circleci.com/workflow-run/9bacda80-7739-41f9-8802-5a2a2a5ea6aa
