### ISSUE TITLE
Monkey patch the API for unit testing

### ISSUE THREAD

**Issue by sr-gi** [talaia-labs/python-teos#77]
After #76 mocks can be easily created to test the API.

**Comment by sr-gi** [comment]
The API thread keeps running until the test suit finished execution, causing some exceptions to raise. They do no affect the tests but they are pretty annoying. 

Monkeypatching the API would also solve this.

e.g.

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sergi/git/python-teos/teos/watcher.py", line 210, in do_watch
    self.db_manager.store_last_block_hash_watcher(block_hash)
  File "/Users/sergi/git/python-teos/teos/db_manager.py", line 388, in store_last_block_hash_watcher
    self.create_entry(WATCHER_LAST_BLOCK_KEY, block_hash)
  File "/Users/sergi/git/python-teos/teos/db_manager.py", line 113, in create_entry
    self.db.put(key, value)
  File "plyvel/_plyvel.pyx", line 314, in plyvel._plyvel.DB.put
RuntimeError: Database is closed
```

This is caused because the API thread keeps running (with the `Watcher` and `Responder` running)  but the database is closed. Mining a new block triggers it.
